# Generated by Django 3.0.5 on 2020-04-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20200422_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spiders',
            new_name='Spider',
        ),
    ]
