# Generated by Django 3.0.5 on 2020-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0005_auto_20200422_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='allowed_domains',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spider',
            name='list_xpath',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spider',
            name='url_contain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spider',
            name='url_no_contain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
