# Generated by Django 3.0.5 on 2020-04-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0007_spider_charset'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='spider_type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='spider',
            name='allowed_domains',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spider',
            name='list_xpath',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spider',
            name='url_contain',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spider',
            name='url_no_contain',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
