# Generated by Django 3.0.5 on 2020-04-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0008_auto_20200424_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='spider_type',
        ),
    ]
