# Generated by Django 3.0.5 on 2020-04-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0009_remove_spider_spider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('account', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('orderNum', models.CharField(max_length=255, null=True)),
                ('imageUrl', models.TextField(null=True)),
                ('sourceUrl', models.TextField(null=True)),
                ('musicUrl', models.TextField(null=True)),
                ('audioUrl', models.TextField(null=True)),
                ('updateTime', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('originalFlag', models.CharField(max_length=255, null=True)),
                ('readNum', models.CharField(max_length=255, null=True)),
                ('likeNum', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('keywords', models.TextField(null=True)),
            ],
        ),
    ]
